import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
import '../../../../localization/app_localizations.dart';
import '../../../../utils/constants/app_vectors.dart';
import '../../models/country.dart';

final List<Country> countries = [
  Country('+61', 'AU', 'Австралия', 'Australia', AppVectors.aus),
  Country('+43', 'AT', 'Австрия', 'Austria', AppVectors.aut),
  Country('+994', 'AZ', 'Азербайджан', 'Azerbaijan', AppVectors.aze),
  Country('+358', 'AX', 'Аландские острова', 'Åland', AppVectors.ala),
  Country('+355', 'AL', 'Албания', 'Shqipëri', AppVectors.ala),
  Country('+213', 'DZ', 'Алжир', 'Algeria', AppVectors.dza),
  Country('+1', 'AS', 'Американское Самоа', 'American Samoa', AppVectors.asm),
  Country('+1', 'AI', 'Ангилья', 'Angullia', AppVectors.aia),
  Country('+376', 'AD', 'Андорра', 'Andorra', AppVectors.and),
  Country('+1', 'AG', 'Антигуа и Барбуда', 'Antigua & Barbuda', AppVectors.atg),
  Country('+244', 'AO', 'Ангола', 'Angola', AppVectors.ago),
  Country('+54', 'AR', 'Аргентина', 'Argentina', AppVectors.arg),
  Country('+374', 'AM', 'Армения', 'Հայաստան', AppVectors.arm),
  Country('+297', 'AW', 'Аруба', 'Aruba', AppVectors.abw),
  Country('+93', 'AF', 'Афганистан', 'افغانستان', AppVectors.afg),
  Country('+973', 'BH', 'Бахрейн', 'البحرين', AppVectors.bhr),
  Country('+880', 'BD', 'Бангладеш', 'বাংলাদেশ', AppVectors.bgd),
  Country('+880', 'BB', 'Барбадос', 'Barbados', AppVectors.brb),
  Country('+375', 'BY', 'Беларусь', '', AppVectors.blr),
  Country('+32', 'BE', 'Бельгия', 'Belgiё', AppVectors.bel),
  Country('+501', 'BZ', 'Белиз', 'Belize', AppVectors.blz),
  Country('+229', 'BJ', 'Бенин', 'Bénin', AppVectors.ben),
  Country('+441', 'BM', 'Бермудские острова', 'Bermuda', AppVectors.bmu),
  Country('+975', 'BT', 'Бутан', 'འབྲུག་ཡུལ', AppVectors.btn),
  Country('+591', 'BO', 'Боливия', 'Bolivia', AppVectors.bol),
  Country('+535', 'BQ', 'Бонайре, Синт-Эстатиус и Саба', 'Bonaire, Sint Eustatius en Saba', AppVectors.bon),
  Country('+387', 'BA', 'Босния и Герциговина', 'Bosna i Hercegovina', AppVectors.bih),
  Country('+267', 'BW', 'Ботсвана', 'Botswana', AppVectors.bwa),
  Country('+55', 'BR', 'Бразилия', 'Brasil', AppVectors.bra),
  Country('+246', 'IO', 'Британская территория Индийского океана', 'British Indian Ocean Territory', AppVectors.iot),
  Country('+673', 'BN', 'Бруней', 'بروني', AppVectors.brn),
  Country('+359', 'BG', 'Болгария', 'България', AppVectors.bgr),
  Country('+1242', 'BS', 'Багамы', 'Bahamas', AppVectors.bhs),
  Country('+226', 'BF', 'Буркина-Фасо', 'Burkina Faso', AppVectors.bfa),
  Country('+257', 'BI', 'Бурунди', 'Burundi', AppVectors.bdi),
  Country('+47', 'BV', 'Буве остров', 'Bouvetøya', AppVectors.bvt),
  Country('+678', 'VU', 'Вануату', 'Vanuatu', AppVectors.vut),
  Country('+379', 'VA', 'Ватикан', 'Civitas Vaticana', AppVectors.vat),
  Country('+44', 'GB', 'Великобритания', 'United Kingdom', AppVectors.gbr),
  Country('+36', 'HU', 'Венгрия', 'Magyarország', AppVectors.hun),
  Country('+58', 'VE', 'Венесуэла', 'Venezuela', AppVectors.ven),
  Country('+850', 'VI', 'Виргинские Острова (США)','U.S Virgin Islands', AppVectors.vir),
  Country('+092', 'VG', 'Виргинские Острова (Великобритания)', 'British Virgin Islands', AppVectors.vgb),
  Country('+670', 'TL', 'Восточный Тимор','Timor Lorosa’e', AppVectors.tls),
  Country('+84', 'VN', 'Вьетнам', 'Việt Nam', AppVectors.vnm),
  Country('+241', 'GA', 'Габон', 'Gabon', AppVectors.gab),
  Country('+220', 'GM', 'Гамбия', 'Gambia', AppVectors.gmb),
  Country('+590', 'GP', 'Гваделупа', 'Guadeloupe', AppVectors.guf),
  Country('+995', 'GE', 'Грузия', 'საქართველო', AppVectors.geo),
  Country('+49', 'DE', 'Германия', 'Deutschland', AppVectors.deu),
  Country('+44', 'GG', 'Гернси', 'Guernsey', AppVectors.ggy),
  Country('+350', 'GI', 'Гибралтар', 'Gibraltar', AppVectors.gib),
  Country('+30', 'GR', 'Греция', 'Ελλάδα', AppVectors.grc),
  Country('+299', 'GL', 'Гренландия', 'Kalaallit Nunaat', AppVectors.grl),
  Country('+502', 'GT','Гватемала', 'Guatemala', AppVectors.gtm),
  Country('+224', 'GN', 'Гвинея', 'Guinée', AppVectors.gin),
  Country('+245', 'GW', 'Гвинея-Бисау', 'Guiné-Bissau', AppVectors.gnb),
  Country('+592', 'GY', 'Гайана', 'Guyana', AppVectors.guy),
  Country('+509', 'HT', 'Гаити', 'Haïti', AppVectors.hti),
  Country('+504', 'HN', 'Гондурас', 'Honduras', AppVectors.hnd),
  Country('+852', 'HK', 'Гонконг', '香港', AppVectors.hkg),
  Country('+473', 'GD', 'Гренада', 'Grenada', AppVectors.grd),
  Country('+995', 'GU', 'Гуам', 'Guinée', AppVectors.gum),
  Country('+45', 'DK', 'Дания', 'Danmark', AppVectors.dnk),
  Country('+832', 'JE', 'Джерси', 'Jersey', AppVectors.jey),
  Country('+253', 'DJ', 'Джибути', 'جيبوتي,', AppVectors.dji),
  Country('+1767', 'DM', 'Доминика', 'Dominica', AppVectors.dma),
  Country('+809', 'DO', 'Республика Доминикана', 'República Dominicana', AppVectors.dom),
  Country('+20', 'EG', 'Египет', 'مصر', AppVectors.egy),
  Country('+260', 'ZM', 'Замбия', 'Zambia', AppVectors.zmb),
  Country('+263', 'ZW', 'Зимбабве', 'Zimbabwe', AppVectors.zwe),
  Country('+972', 'IL', 'Израиль', '‏יִשְׂרָאֵל,', AppVectors.isr),
  Country('+91', 'IN', 'Индия', 'भारतहिंदुस्तान', AppVectors.ind),
  Country('+62', 'ID', 'Индонезия', 'Indonesia', AppVectors.idn),
  Country('+962', 'JO', 'Иордания','الأردن', AppVectors.jor),
  Country('+98', 'IR', 'Иран', 'ایران', AppVectors.irn),
  Country('+964', 'IQ', 'Ирак', 'الْعِرَاق', AppVectors.irq),
  Country('+353', 'IE', 'Ирландия','Éire', AppVectors.irl),
  Country('+354', 'IS', 'Исландия','Iceland', AppVectors.isl),
  Country('+34', 'ES', 'Испания', 'España', AppVectors.esp),
  Country('+39', 'IT', 'Италия', 'Italia', AppVectors.ita),
  Country('+967', 'YE', 'Йемен', 'ٱلْيَمَن', AppVectors.yem),
  Country('+7', 'KZ', 'Казахстан', 'Қазақстан', AppVectors.kaz),
  Country('+254', 'KE', 'Кения', 'Kenya', AppVectors.ken),
  Country('+686', 'KI', 'Кирибати', 'Kiribati', AppVectors.kir),
  Country('+855', 'KH', 'Камбоджа', 'កម្ពុជា', AppVectors.khm),
  Country('+237', 'CM', 'Камерун', 'Cameroun', AppVectors.cmr),
  Country('+1', 'CA', 'Канада', 'Canada', AppVectors.can),
  Country('+238', 'CV', 'Кабо-Верде', 'Cabo Verde', AppVectors.cpv),
  Country('+1345', 'KY', 'Каймановы Острова', 'Cayman Islands', AppVectors.cym),
  Country('+34', 'CT', 'Каталония', 'Catalunya', AppVectors.cat),
  Country('+974', 'QA', 'Катар', 'قطر', AppVectors.qat),
  Country('+86', 'CN', 'Китай', '中国', AppVectors.chn),
  Country('+506', 'CR', 'Коста-Рика', 'Costa Rica', AppVectors.cri),
  Country('+383', 'XK', 'Косово', 'Kosovё', AppVectors.kos),
  Country('+53', 'CU', 'Куба', 'Cuba', AppVectors.cub),
  Country('+599', 'CW', 'Кюрасао', 'Land Curaçao', AppVectors.cuw),
  Country('+357', 'CY', 'Кипр', 'Κύπρος', AppVectors.cyp),
  Country('+61', 'CC', 'Кокосовые острова', 'Kapelauan Cocos (Keepling)', AppVectors.cck),
  Country('+57', 'CO', 'Колумбия', 'Colombia', AppVectors.col),
  Country('+242', 'CG', 'Конго-Браззавиль', 'Congo-Brazzaville', AppVectors.cog),
  Country('+269', 'KM', 'Коморы', 'Komori', AppVectors.com),
  Country('+225', 'CI', 'Кот-д`Ивуар', 'Côte d’Ivoire', AppVectors.civ),
  Country('+965', 'KW', 'Кувейт', 'الكويت', AppVectors.kwt),
  Country('+996', 'KG', 'Киргизия', 'Кыргызстан', AppVectors.kgz),
  Country('+856', 'LA', 'Лаос', 'ລາວ', AppVectors.lao),
  Country('+371', 'LV', 'Латвия', 'Latvija', AppVectors.lva),
  Country('+961', 'LB', 'Ливан', 'لُبْنَان', AppVectors.lbn),
  Country('+266', 'LS', 'Лесото', 'Lesotho', AppVectors.lso),
  Country('+231', 'LR', 'Либерия', 'Liberia', AppVectors.lbr),
  Country('+218', 'LY', 'Ливия', 'ليبيا', AppVectors.lby),
  Country('+423', 'LI', 'Лихтенштейн', 'Liechtenstein', AppVectors.lie),
  Country('+370', 'LT', 'Литва', 'Lietuva', AppVectors.ltu),
  Country('+352', 'LU', 'Люксембург', 'Lëtzebuerg', AppVectors.lux),
  Country('+853', 'MO', 'Макао', '澳門', AppVectors.mac),
  Country('+261', 'MG', 'Мадагаскар', 'Madagasikara', AppVectors.mdg),
  Country('+265', 'MW', 'Малави', 'Malawi', AppVectors.mwi),
  Country('+212', 'MA', 'Марокко', 'المغرب', AppVectors.mar),
  Country('+60', 'MY', 'Малайзия', 'Malaysia', AppVectors.mys),
  Country('+960', 'MV', 'Мальдивы', 'ހިވެދި ގުޖޭއްރާ', AppVectors.mdv),
  Country('+223', 'ML', 'Мали','Mali', AppVectors.mli),
  Country('+356', 'MT', 'Мальта','Malta', AppVectors.mlt),
  Country('+692', 'MH', 'Маршалловы острова', 'Marshall Islands', AppVectors.mhl),
  Country('+222', 'MR', 'Мавритания', 'موريتانيا', AppVectors.mrt),
  Country('+230', 'MU', 'Маврикий', 'Mauritius', AppVectors.mus),
  Country('+262', 'YT', 'Майотта', 'Mayotte', AppVectors.wlf),
  Country('+52', 'MX', 'Мексика', 'México', AppVectors.mex),
  Country('+691', 'FM', 'Микронезия', 'Micronesia', AppVectors.fsm),
  Country('+373', 'MD', 'Молдавия', 'Moldova', AppVectors.mda),
  Country('+377', 'MC', 'Монако', 'Monaco', AppVectors.mco),
  Country('+976', 'MN', 'Монголия', 'Montserrat', AppVectors.mng),
  Country('+1664', 'MS', 'Монтсеррат', 'Монгол Улс', AppVectors.msr),
  Country('+95', 'MM', 'Мьянма (Бирма)','မြန်မာ', AppVectors.mmr),
  Country('+258', 'MZ', 'Мозамбик', 'Moçambique', AppVectors.moz),
  Country('+264', 'NA', 'Намибия', 'Namibia', AppVectors.nam),
  Country('+674', 'NR', 'Науру', 'Naoero', AppVectors.nru),
  Country('+977', 'NP', 'Непал', 'नेपाल', AppVectors.npl),
  Country('+31', 'NL', 'Нидерланды', 'Nederland', AppVectors.nld),
  Country('+687', 'NC', 'Новая Каледония', 'Nouvelle-Calédonie', AppVectors.ncl),
  Country('+64', 'NZ', 'Новая Зеландия', 'New Zealand', AppVectors.nzl),
  Country('+505', 'NI', 'Никарагуа', 'Nicaragua', AppVectors.nzl),
  Country('+227', 'NE', 'Нигер', 'Niger', AppVectors.ner),
  Country('+234', 'NG', 'Нигерия', 'Nigeria', AppVectors.nga),
  Country('+683', 'NU', 'Ниуэ', 'Niue', AppVectors.niu),
  Country('+47', 'NO', 'Норвегия', 'Norge', AppVectors.nor),
  Country('+971', 'AE', 'Объединенные Арабские Эмираты', 'الإمارات,', AppVectors.are),
  Country('+968', 'OM', 'Оман', 'عُمان', AppVectors.omn),
  Country('+247', 'AC', 'Остров Вознесения', 'Ascension Island', AppVectors.asi),
  Country('+44', 'IM', 'Остров Мэн', 'Isle of Man', AppVectors.imn),
  Country('+682', 'CK', 'Острова Кука', 'Cook Islands', AppVectors.cok),
  Country('+870', 'PN', 'Острова Питкэрн', 'Pitcairn Islands', AppVectors.pcn),
  Country('+61', 'CX', 'Остров Рождества', 'Christmas Island', AppVectors.cxr),
  Country('+290', 'SH', 'Остров Святой Елены', 'St. Elena Island', AppVectors.shn),
  Country('+599', 'KY', 'Острова Кайман', 'Cayman Islands', AppVectors.cym),
  Country('+92', 'PK', 'Пакистан', 'پاکستان', AppVectors.pak),
  Country('+970', 'PS', 'Палестина', 'دولة فلسطي', AppVectors.pse),
  Country('+680', 	'PW', 'Палау', 'Palau', AppVectors.plw),
  Country('+507', 'PA', 'Панама', 'Panamá', AppVectors.pan),
  Country('+675', 'PG', 'Папуа - Новая Гвинея', 'Papua New Guinea', AppVectors.png),
  Country('+595', 'PY', 'Парагвай', 'Paraguay', AppVectors.pry),
  Country('+51', 'PE', 'Перу', 'Perú', AppVectors.per),
  Country('+48', 'PL', 'Польша', 'Polska', AppVectors.pol),
  Country('+351', 'PT', 'Португалия', 'Portugal', AppVectors.prt),
  Country('+620', 'PR', 'Пуэрто-Рико', 'Puerto Rico', AppVectors.pri),
  Country('+262', 'RE', 'Реюньон', 'Réunion', AppVectors.reu),
  Country('+7', 'RU', 'Россия', 'Russia', AppVectors.rus),
  Country('+250', 'RW', 'Руанда', 'Rwandan', AppVectors.rwa),
  Country('+40', 'RO', 'Румыния', 'România', AppVectors.rou),
  Country('+503', 'SV', 'Сальвадор', 'El Salvador', AppVectors.slv),
  Country('+685', 'WS', 'Самоа', 'Samoa', AppVectors.wsm),
  Country('+378', 'SM', 'Сан-Марино', 'San Marino', AppVectors.smr),
  Country('+239', 'ST', 'Сан-Томе и Принсипи', 'São Tomé and Príncipe', AppVectors.stp),
  Country('+966', 'SA', 'Саудовская Аравия', 'ٱلسُّعُوْدِيَّة العربيّة', AppVectors.sau),
  Country('+389', 'MK', 'Северная Македония', 'Северна Македонија', AppVectors.mkd),
  Country('+1670', 'MP', 'Северные Марианские Острова', 'Northern Mariana Islands', AppVectors.mnp),
  Country('+590', 'BL', 'Сен-Бартелеми', 'Saint-Barthélemy', AppVectors.wlf),
  Country('+850', 'KP', 'Северная Корея', '北朝鮮', AppVectors.prk),
  Country('+221', 'SN', 'Сенегал', 'Sénégal', AppVectors.sen),
  Country('+221', 'VC', 'Сент-Винсент и Гренадины', 'St. Vincent & Grenadines', AppVectors.vct),
  Country('+659', 'KN', 'Сент-Китс и Невис', 'St. Kitts &amp; Nevis', AppVectors.kna),
  Country('+221', 'LC', 'Сент-Люсия', 'Saint Lucia', AppVectors.ica),
  Country('+381', 'RS', 'Сербия', 'Србија', AppVectors.srb),
  Country('+248', 'SC', 'Сейшельские острова', 'Sesel', AppVectors.syc),
  Country('+232', 'SL', 'Сьерра-Леоне', 'Sierra Leone', AppVectors.sle),
  Country('+65', 'SG', 'Сингапур', 'Singapura', AppVectors.sgp),
  Country('+534', 'SX', 'Синт-Мартен', 'Sint Maarten', AppVectors.wlf),
  Country('+421', 'SK', 'Словакия', 'Slovensko', AppVectors.svk),
  Country('+386', 'SI', 'Словения', 'Slovenija', AppVectors.svn),
  Country('+1', 'US', 'Соединенные Штаты Америки', 'United States of America', AppVectors.usa),
  Country('+677', 'SB', 'Соломоновы острова', 'Solomon Islands', AppVectors.slb),
  Country('+252', 'SO', 'Сомали', 'Soomaaliya', AppVectors.som),
  Country('+508', 'PM', 'Сен-Пьер и Микелон', 'Saint-Pierre et Miquelon', AppVectors.spm),
  Country('+249', 'SD', 'Судан', 'السودان', AppVectors.sdn),
  Country('+597', 'SR', 'Суринам', 'Suriname', AppVectors.sur),
  Country('+963', 'SY', 'Сирия', 'سُورِيَة', AppVectors.syr),
  Country('+886', 'TW', 'Тайвань', '台灣', AppVectors.twn),
  Country('+992', 'TJ', 'Таджикистан', 'Тоҷикистон', AppVectors.tjk),
  Country('+255', 'TZ', 'Танзания', 'Tanzania', AppVectors.tza),
  Country('+66', 'TH', 'Таиланд', 'ประเทศไทย', AppVectors.tha),
  Country('+228', 'TG', 'Того', 'Togo,', AppVectors.tgo),
  Country('+690', 'TK', 'Токелау', 'Tokelau,', AppVectors.tkl),
  Country('+676', 'TO', 'Тонга', 'Tonga', AppVectors.ton),
  Country('+1868', 'TT', 'Тринидад и Тобаго', 'Trinidad & Tobago', AppVectors.tto),
  Country('+216', 'TN', 'Тунис', 'تونس', AppVectors.tun),
  Country('+90', 'TR', 'Турция', 'Türkiye', AppVectors.tur),
  Country('+993', 'TM', 'Туркменистан', 'Türkmenistan', AppVectors.tkm),
  Country('+688', 'TV', 'Тувалу', 'Tuvalu', AppVectors.tuv),
  Country('+256', 'UG', 'Уганда', 'Uganda', AppVectors.uga),
  Country('+380', 'UA', 'Украина', 'Україна', AppVectors.ukr),
  Country('+598', 'UY', 'Уругвай', 'Uruguay', AppVectors.ury),
  Country('+998', 'UZ', 'Узбекистан', 'Oʻzbekiston', AppVectors.uzb),
  Country('+681', 'WF', 'Уоллис и Футуна', 'Wallis-et-Futuna', AppVectors.wlf),
  Country('+298', 'FO', 'Фарерские острова', '', AppVectors.fro),
  Country('+679', 'FJ', 'Фиджи', 'Fiji', AppVectors.fji),
  Country('+63', 'PH', 'Филиппины', 'Pilipinas', AppVectors.phl),
  Country('+358', 'FI', 'Финляндия', 'Suomi', AppVectors.fin),
  Country('+500', 'FK', 'Фолклендские острова', 'Falkland Islands', AppVectors.flk),
  Country('+33', 'FR', 'Франция', 'France', AppVectors.fra),
  Country('+689', 'PF', 'Французская Полинезия', 'Polynésie française', AppVectors.pyf),
  Country('+594', 'GF', 'Французская Гвиана', 'Guyane Française', AppVectors.giu),
  Country('+385', 'HR', 'Хорватия', 'Hrvatska', AppVectors.hrv),
  Country('+236', 'CF', 'Центрально-Африканская Республика', 'République Centrafricaine', AppVectors.caf),
  Country('+235', 'TD', 'Чад', 'Tchad', AppVectors.tcd),
  Country('+382', 'ME', 'Черногория', 'Црна Гора / Crna Gora', AppVectors.mne),
  Country('+420', 'CZ', 'Чехия', 'Česko', AppVectors.cze),
  Country('+56', 'CL', 'Чили', 'Chile', AppVectors.chl),
  Country('+41', 'CH', 'Швейцария', 'Schweiz', AppVectors.che),
  Country('+46', 'SE', 'Швеция', 'Sverige', AppVectors.swe),
  Country('+94', 'LK', 'Шри-Ланка', 'ශ්‍රී ලංකාව', AppVectors.lka),
  Country('+47', 'SJ', 'Шпицберген', 'Svalbard', AppVectors.nor),
  Country('+240', 'GQ', 'Экваториальная Гвинея', 'Guinea Ecuatorial', AppVectors.gnq),
  Country('+593', 'EC', 'Эквадор', 'Ecuador', AppVectors.ecu),
  Country('+291', 'ER', 'Эритрея', 'إرتريا', AppVectors.eri),
  Country('+268', 'SZ', 'Эсватини', 'Eswatini', AppVectors.swz),
  Country('+372', 'EE', 'Эстония', 'Eesti', AppVectors.est),
  Country('+251', 'ET', 'Эфиопия', 'ኢትዮጵያ', AppVectors.eth),
  Country('+27', 'ZA', 'Южная Африка', 'South Africa', AppVectors.zaf),
  Country('+82', 'KR', 'Южная Корея', '南韓', AppVectors.kor),
  Country('+211', 'SS', 'Южный Судан', 'South Sudan', AppVectors.ssd),
  Country('+876', 'JM', 'Ямайка', 'Jamaica', AppVectors.jam),
  Country('+81', 'JP', 'Япония', '日本', AppVectors.jpn),
];

Widget buildCountryList(BuildContext context) {
  final localizations = AppLocalizations.of(context);

  return ListView.builder(
    itemCount: countries.length,
    itemBuilder: (context, index) {
      final country = countries[index];
      final countryName = localizations.translate('countries.${country.name}');

      return ListTile(leading: SvgPicture.asset(country.flag), title: Text(countryName), subtitle: Text(country.nativeName));
    },
  );
}

String? getCountryNameByCode(String code) {
  final country = countries.firstWhere((country) => country.code.replaceAll('+', '') == code.replaceAll('+', ''), orElse: () => Country('', '', '', '', ''));

  return country.name.isNotEmpty ? country.name : null;
}
